version: "3.8"
services:
   #webserv:
   #   #image: httpd:latest
   #   build:
   #      context: ./web-serv/
   #      dockerfile: Dockerfile
   #   volumes:
         #- ./web-serv/www:/usr/local/apache2/htdocs
    #     - ./web-serv/laravel:/usr/local/apache2/htdocs
         # Copiamos el config de INI para poder añadir acceder a todas las funcionalidades PDO DE LARAVEL
    #     - ./web-serv/conf/php.ini:/usr/local/etc/php/php.ini
   #  ports:
   #      - "3007:80"
   #      - "3008:8000"
   #Pendiente de arreglar
   nginx:
      build:
         context: ./nginx/
         dockerfile: Dockerfile
      #image: revanhub/nginx-integracion:latest
      ports:
         - 3007:80
      # Importo los archivos de Laravel / Config de NginX respectivamente
      volumes: 
         - ./nginx/www/:/var/www/html
         - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      environment:
         - NGINX_PORT=80
      links:
         - db
         - php-fpm
      depends_on:
         - php-fpm
   # servidor PHP para nginx
   php-fpm:
      build:
         context: ./php-fpm/
         dockerfile: Dockerfile
      #image: php:8-fpm
   #   # Importo el config de php si es necesario
      volumes:
         - ./nginx/www/:/var/www/html
   db:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /mysql/sql/:/var/lib/mysql
    restart: always
   pma:
      image: phpmyadmin/phpmyadmin
      links:
         - db:db
      ports:
         - "8001:80"
      environment:
         PMA_HOST: db
         PMA_USER: root
         PMA_PASSWORD: example
#volumes:
#   persistent:
networks:
   default: