version: "3.8"
services:
   webserv:
      build:
         context: ./web-serv/
         dockerfile: Dockerfile
      volumes:
         #- ./web-serv/www:/var/www/html
         - ./web-serv/laravel:/var/www/html
         # Copiamos el config de INI para poder añadir acceder a todas las funcionalidades PDO DE LARAVEL
         - ./web-serv/conf/php.ini:/usr/local/etc/php/php.ini
      ports:
         - "3008:80"
         - "3009:8000"
   nginx:
      build:
         context: ./nginx/
         dockerfile: Dockerfile
      #image: revanhub/nginx-integracion:latest
      ports:
         - "3007:80" # Puerto de Nginx Básico
      # Importo los archivos de Laravel / Config de NginX respectivamente
      volumes: 
         #Integrados archivos de la API
         - ./nginx/api/:/var/www/html #No cambiar
         - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      environment:
         - NGINX_PORT=80
      links:
         - db
         - php-fpm
      depends_on:
         - php-fpm
   #api:
   #   build:
   #      context: ./api/
   #      dockerfile: Dockerfile
      #image: revanhub/nginx-integracion:latest
   #   ports:
   #      - "8000:8000" # Puerto de Nginx API Escucha
   #   volumes: 
         #Integrados archivos de la API
   #      - ./api/api/:/var/www/html
   #      - ./api/php/php.ini:/etc/php/8.2/cli/php.ini # Copio la config de PHP 
      # Suaviza la recursividad dns evitando periodos de grandes latencias
   #   dns: 
   #      - 8.8.8.8
   #      - 4.4.4.4
   #   links:
   #      - db
   # servidor PHP para nginx
   php-fpm:
      build:
         context: ./php-fpm/
         dockerfile: Dockerfile
      #image: php:8-fpm
      volumes: 
         # Integrados archivos de la API
         - ./nginx/api/:/var/www/html # No cambiar
   db:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: api_integracion
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /mysql/sql/:/docker-entrypoint-initdb.d/
    restart: always
   pma:
      image: phpmyadmin/phpmyadmin
      links:
         - db:db
      ports:
         - "8001:80"
networks:
   default: