version: "3.8"
services:
   webserv:
      build:
         context: ./web-serv/
         dockerfile: Dockerfile
      #image: httpd
      volumes:
         - ./web-serv/www:/var/www/html
         - ./web-serv/laravel:/var/www/html
      ports:
         - 3007:80
         - 3008:8000
   #Pendiente de arreglar
   #nginx:
   #   build:
   #      context: ./nginx/
   #      dockerfile: Dockerfile
      #image: revanhub/nginx-integracion:latest
   #   ports:
   #      - 3007:80
      # Importo los archivos de Laravel / Config de NginX respectivamente
   #   volumes: 
   #      - ./nginx/www/:/usr/share/nginx/html
   #      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
   #   environment:
   #      - NGINX_PORT=80
   #   links:
   #      - db
   #   depends_on:
   #      - php-fpm
   # servidor PHP para nginx
   #php-fpm:
   #   build:
   #      context: ./php-fpm/
   #      dockerfile: Dockerfile
   #   #image: php:8.2-fpm-alpine  
   #   # Importo el config de php si es necesario
   #   volumes:
   #      - ./nginx/www/:/var/www/html
   db:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /mysql/sql/:/var/lib/mysql
    restart: always

   adminer:
      image: adminer
      restart: always
      ports:
         - 8080:8080
   #pma:
   #   image: phpmyadmin/phpmyadmin
   #   links:
   #      - db:db
   #   ports:
   #      - 8000:8001
   #   environment:
   #      MYSQL_USER: laravel
   #      MYSQL_PASSWORD: laravel_app
   #      MYSQL_ROOT_PASSWORD: laravel_app
volumes:
   persistent:
networks:
   default: