FROM 'mysql'
LABEL description="Servicio de MySQL"

# Crea las variables de entorno
#ENV MYSQL_PORT=3306
#ENV MYSQL_ROOT_PASSWORD=deploy_integracion
#ENV MYSQL_USER=deploy
#ENV MYSQL_PASSWORD=ik8uj78yh6tg5Fr4D3eWS2


# Asigna la base de datos inicial
#COPY ./sql/db.sql /docker-entrypoint-initdb.d
EXPOSE 3306 
